### ISSUE TITLE
Issue while setting it up on mac

### ISSUE THREAD

**Issue by smitthakkar96** [distributed-system-analysis/sarjitsu#36]
Below is the traceback

```  traceback
Traceback (most recent call last):
  File "/Users/smit/Documents/redhat/sarjitsu/venv/lib/python3.6/site-packages/flask/app.py", line 1997, in __call__
    return self.wsgi_app(environ, start_response)
  File "/Users/smit/Documents/redhat/sarjitsu/venv/lib/python3.6/site-packages/flask/app.py", line 1985, in wsgi_app
    response = self.handle_exception(e)
  File "/Users/smit/Documents/redhat/sarjitsu/venv/lib/python3.6/site-packages/flask/app.py", line 1540, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/smit/Documents/redhat/sarjitsu/venv/lib/python3.6/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/Users/smit/Documents/redhat/sarjitsu/venv/lib/python3.6/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/smit/Documents/redhat/sarjitsu/venv/lib/python3.6/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/smit/Documents/redhat/sarjitsu/venv/lib/python3.6/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/smit/Documents/redhat/sarjitsu/venv/lib/python3.6/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/Users/smit/Documents/redhat/sarjitsu/venv/lib/python3.6/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/smit/Documents/redhat/sarjitsu/venv/lib/python3.6/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/smit/Documents/redhat/sarjitsu/lib/backend/src/server.py", line 70, in uploader
    session.sid, form)
  File "/Users/smit/Documents/redhat/sarjitsu/lib/backend/src/upload_processor.py", line 86, in begin
    for filename in filename_list:
TypeError: 'NoneType' object is not iterable
```

**Comment by arcolife** [comment]
IIRC you were later able to setup sarjitsu with docker-compose on a Fedora in a VM. Right?

more so, the SA binary files in vos.analysis.lib.bin folder give out an executable file format. `OSError: [Errno 8] Exec format error` on OS X. This is because sysstat is not supported on Mac OS yet. https://github.com/sysstat/sysstat/issues/74#issuecomment-123200535 

Closing this issue as its out of scope. Will add changes to README about developer setup compatibility.
